### ISSUE TITLE
YulDeployer could not deploy contract

### ISSUE THREAD

**Issue by ChinW** [crystalbit/deploy-yul#1]
solidity is v0.8.13, tried quite some basic yul setup examples, but all failed in below error in the end, wonder if this still works, appreciated for any ideas :D

```
Failing tests:
Encountered 1 failing test in test/Counter.t.sol:CounterTest
[FAIL. Reason: revert: YulDeployer could not deploy contract] test_Increment() (gas: 8937393460516758944)
```

**Comment by crystalbit** [comment]
Hi! Could you pls give contract example and solidity version?

**Comment by ChuaShuErn** [comment]
Hi, I am also having a similar Issue.

Solidity version 0.8.24

Yul Contract Example:
```yul 
object "Basic" {
  code {
    datacopy(0, dataoffset("Runtime"), datasize("Runtime"))
    return(0, datasize("Runtime"))
  }
  object "Runtime" {
    code {
      let sum := add(3, 5)
      mstore(0x0, sum)
      return(0x0, 0x20)
    }
  }
}
```

Logs after running `forge test -vvvv`. 

[⠒] Compiling...
[⠃] Compiling 2 files with 0.8.24
[⠊] Solc 0.8.24 finished in 792.52ms
Compiler run successful!
2024-02-02T17:20:37.378656Z ERROR forge::runner: setUp failed reason=revert: YulDeployer could not deploy contract contract=0x7FA9385bE102ac3EAc297483Dd6233D62b3e1496

Running 1 test for test/Basic.t.sol:BasicTest
[FAIL. Reason: setup failed: revert: YulDeployer could not deploy contract] setUp() (gas: 0)
Logs:
  0x600b600b5f39600b5ff3fe60056003015f5260205ff3

Traces:
  [8937393460516729930] BasicTest::setUp()
    ├─ [8937393460516724883] YulDeployer::deployContract("Basic")
    │   ├─ [0] VM::ffi(["bash", "-c", "cast abi-encode \"f(bytes)\" $(solc --strict-assembly yul/Basic.yul --bin | tail -1)"])
    │   │   └─ ← 0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000016600b600b5f39600b5ff3fe60056003015f5260205ff300000000000000000000
    │   ├─ [0] console::logBytes(0x600b600b5f39600b5ff3fe60056003015f5260205ff3) [staticcall]
    │   │   └─ ← ()
    │   ├─ [6] → new <unknown>@0x104fBc016F4bb334D775a19E8A6510109AC63E00
    │   │   └─ ← 22 bytes of code
    │   └─ ← revert: YulDeployer could not deploy contract
    └─ ← revert: YulDeployer could not deploy contract

Test result: FAILED. 0 passed; 1 failed; 0 skipped; finished in 43.11ms
 
Ran 1 test suites: 0 tests passed, 1 failed, 0 skipped (1 total tests)

Failing tests:
Encountered 1 failing test in test/Basic.t.sol:BasicTest
[FAIL. Reason: setup failed: revert: YulDeployer could not deploy contract] setUp() (gas: 0)

Encountered a total of 1 failing tests, 0 tests succeeded

When I tried to `console.logBytes(bytecode`, output is `0x600b600b5f39600b5ff3fe60056003015f5260205ff3`

Please advise, thank you

**Comment by crystalbit** [comment]
Hmmm, will check now. Thank you for info

**Comment by crystalbit** [comment]
I had no problems with older foundry and after foundryup currently. Could you pls share also your test file?

**Comment by crystalbit** [comment]
I just made an example repo which works for me: https://github.com/crystalbit/yul-deploy-test

You may also check if it works for you and check differences. If it doesn't, I'll dig deeper

**Comment by ChuaShuErn** [comment]
Thank you for helping to check.

Test File:

```sol
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import "forge-std/Test.sol";
import "deploy-yul/BytecodeDeployer.sol";
import "deploy-yul/YulDeployer.sol";
import "forge-std/console.sol";

contract BasicTest is Test {
    YulDeployer yulDeployer = new YulDeployer();
    BytecodeDeployer bytecodeDeployer = new BytecodeDeployer();
    address basic;
    address basicBytecode;

    function setUp() external {
        basic = yulDeployer.deployContract("Basic");
        basicBytecode = bytecodeDeployer.deployContract("Basic");
    }

    function testBasic() external {
        (bool success, bytes memory result) = basic.staticcall("");
        assertEq(uint256(bytes32(result)), 8);
        assertTrue(success);
    }

    function testBasicBytecode() external {
        (bool success, bytes memory result) = basicBytecode.staticcall("");
        assertEq(uint256(bytes32(result)), 8);
        assertTrue(success);
    }
}

```

YulDeployer.sol

```sol

// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

// https://github.com/CodeForcer/foundry-yul/blob/main/test/lib/YulDeployer.sol
// modified by me: changed --yul to --strict-assembly in line 15

import "forge-std/Test.sol";
import "forge-std/console.sol";
contract YulDeployer is Test {
  ///@notice Compiles a Yul contract and returns the address that the contract was deployeod to
  ///@notice If deployment fails, an error will be thrown
  ///@param fileName - The file name of the Yul contract. For example, the file name for "Example.yul" is "Example"
  ///@return deployedAddress - The address that the contract was deployed to
  function deployContract(string memory fileName) public returns (address) {
    string memory bashCommand = string.concat('cast abi-encode "f(bytes)" $(solc --strict-assembly yul/', string.concat(fileName, ".yul --bin | tail -1)"));

    string[] memory inputs = new string[](3);
    inputs[0] = "bash";
    inputs[1] = "-c";
    inputs[2] = bashCommand;

    bytes memory bytecode = abi.decode(vm.ffi(inputs), (bytes));

    console.logBytes(bytecode);
    //output is: 0x600b600b5f39600b5ff3fe60056003015f5260205ff3
    ///@notice deploy the bytecode with the create instruction
    address deployedAddress;
    assembly {
      deployedAddress := create(0, add(bytecode, 0x20), mload(bytecode))
    }

    ///@notice check that the deployment was successful
    require(
      deployedAddress != address(0),
      "YulDeployer could not deploy contract"
    );

    ///@notice return the address that the contract was deployed to
    return deployedAddress;
  }
}
```
I was using the Solidity version `0.8.19`, but I thought it had something to do with my compiler so i tried to install the latest version.

**Comment by ChuaShuErn** [comment]
I've tried using your example repo. These are my logs.

I did `forge build` then `forge test -vvvv`

[⠒] Compiling...
[⠃] Compiling 22 files with 0.8.24
[⠒] Solc 0.8.24 finished in 2.90s
Compiler run successful!
shuernchua@Shus-MacBook-Pro yul-deploy-test % forge test -vvvv
[⠒] Compiling...
No files changed, compilation skipped

Running 1 test for test/Deployer.t.sol:DeployerTest
[FAIL. Reason: revert: YulDeployer could not deploy contract] test_test() (gas: 8937393460516758942)
Traces:
  [8937393460516758942] DeployerTest::test_test()
    ├─ [908959] → new YulDeployer@0x5615dEB798BB3E4dFa0139dFa1b3D433Cc23b72f
    │   └─ ← 4380 bytes of code
    ├─ [8937393460515816553] YulDeployer::deployContract("Basic")
    │   ├─ [0] VM::ffi(["bash", "-c", "cast abi-encode \"f(bytes)\" $(solc --strict-assembly yul/Basic.yul --bin | tail -1)"])
    │   │   └─ ← 0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000016600b600b5f39600b5ff3fe60056003015f5260205ff300000000000000000000
    │   ├─ [0] VM::broadcast()
    │   │   └─ ← ()
    │   ├─ [6] → new <unknown>@0x90193C961A926261B756D1E5bb255e67ff9498A1
    │   │   └─ ← 22 bytes of code
    │   └─ ← revert: YulDeployer could not deploy contract
    └─ ← revert: YulDeployer could not deploy contract

Test result: FAILED. 0 passed; 1 failed; 0 skipped; finished in 42.54ms
 
Ran 1 test suites: 0 tests passed, 1 failed, 0 skipped (1 total tests)

Failing tests:
Encountered 1 failing test in test/Deployer.t.sol:DeployerTest
[FAIL. Reason: revert: YulDeployer could not deploy contract] test_test() (gas: 8937393460516758942)

**Comment by crystalbit** [comment]
Hmm, your test works for me (if I comment out bytecode part):
```
Running 1 test for test/Deployer.t.sol:BasicTest
[PASS] testBasic() (gas: 5331)
Traces:
  [5331] BasicTest::testBasic()
    ├─ [27] 0x90193C961A926261B756D1E5bb255e67ff9498A1::fallback() [staticcall]
    │   └─ ← 0x0000000000000000000000000000000000000000000000000000000000000008
    └─ ← ()

Test result: ok. 1 passed; 0 failed; 0 skipped; finished in 55.55ms
 
Ran 1 test suites: 1 tests passed, 0 failed, 0 skipped (1 total tests)
```

btw I have 0.8.19 too

What is result of `solc --verison`? Pls confirm it is 0.8.19 or not

**Comment by ChuaShuErn** [comment]
My result of `solc --version` is `Version: 0.8.24+commit.e11b9ed9.Darwin.appleclang`

I reinstalled earlier today because I thought that was the problem

**Comment by crystalbit** [comment]
Hehe, just upgraded to 0.8.24 and now I have the problem, too :)
Nice, I will investigate it a bit later and write here

**Comment by crystalbit** [comment]
Idea is that the problem is because of PUSH0:
0.8.19 compiles to `0x600e600d600039600e6000f3fe60056003018060005260206000f3`
0.8.24 compiles to `0x600b600b5f39600b5ff3fe60056003015f5260205ff3` where 5f === PUSH0

And looks like (I don't want to check docs now) foundry environment doesn't support the opcode yet. I will fix it by adding `--evm-version=london` to solc command

**Comment by crystalbit** [comment]
Looks like it is fixed now. Thank you guys!

Btw I don't know about versioning in such libs for foundry :(
